version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  apt_packages:
    - default-jre-headless

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
