# Generated by Grammarinator 17.7r

from itertools import chain
from grammarinator.runtime import *

charset_0 = list(chain(*multirange_diff(printable_unicode_ranges, [(60, 61)])))
charset_1 = list(chain(range(32, 33), range(9, 10), range(13, 14), range(10, 11)))
charset_2 = list(chain(range(97, 103), range(65, 71), range(48, 58)))
charset_3 = list(chain(range(48, 58)))
charset_4 = list(chain(range(58, 59), range(97, 123), range(65, 91)))
charset_5 = list(chain(range(32, 33)))
charset_6 = list(chain(range(48, 58), range(97, 123), range(65, 91)))
charset_7 = list(chain(range(48, 58), range(97, 103), range(65, 71)))
charset_8 = list(chain(range(48, 58)))
charset_9 = list(chain(*multirange_diff(printable_unicode_ranges, [(34, 35),(60, 61)])))
charset_10 = list(chain(*multirange_diff(printable_unicode_ranges, [(39, 40),(60, 61)])))


class HTMLUnlexer(Grammarinator):

    def __init__(self, *, max_depth=float('inf'), weights=None, cooldown=1.0):
        super(HTMLUnlexer, self).__init__()
        self.unlexer = self
        self.max_depth = max_depth
        self.weights = weights or dict()
        self.cooldown = cooldown
        self.set_options()

    def EOF(self, *args, **kwargs):
        pass

    
    def style_sheet(self, *args, **kwargs):
        return UnlexerRule(src='')
    
    @depthcontrol
    def HTML_COMMENT(self):
        current = self.create_node(UnlexerRule(name='HTML_COMMENT'))
        current += self.create_node(UnlexerRule(src='<!--'))
        if self.unlexer.max_depth >= 0:
            for _ in self.zero_or_more():
                current += UnlexerRule(src=self.any_char())

        current += self.create_node(UnlexerRule(src='-->'))
        return current
    HTML_COMMENT.min_depth = 0

    @depthcontrol
    def HTML_CONDITIONAL_COMMENT(self):
        current = self.create_node(UnlexerRule(name='HTML_CONDITIONAL_COMMENT'))
        current += self.create_node(UnlexerRule(src='<!['))
        if self.unlexer.max_depth >= 0:
            for _ in self.zero_or_more():
                current += UnlexerRule(src=self.any_char())

        current += self.create_node(UnlexerRule(src=']>'))
        return current
    HTML_CONDITIONAL_COMMENT.min_depth = 0

    @depthcontrol
    def XML_DECLARATION(self):
        current = self.create_node(UnlexerRule(name='XML_DECLARATION'))
        current += self.create_node(UnlexerRule(src='<?xml'))
        if self.unlexer.max_depth >= 0:
            for _ in self.zero_or_more():
                current += UnlexerRule(src=self.any_char())

        current += self.create_node(UnlexerRule(src='>'))
        return current
    XML_DECLARATION.min_depth = 0

    @depthcontrol
    def CDATA(self):
        current = self.create_node(UnlexerRule(name='CDATA'))
        current += self.create_node(UnlexerRule(src='<![CDATA['))
        if self.unlexer.max_depth >= 0:
            for _ in self.zero_or_more():
                current += UnlexerRule(src=self.any_char())

        current += self.create_node(UnlexerRule(src=']]>'))
        return current
    CDATA.min_depth = 0

    @depthcontrol
    def DTD(self):
        current = self.create_node(UnlexerRule(name='DTD'))
        current += self.create_node(UnlexerRule(src='<!'))
        if self.unlexer.max_depth >= 0:
            for _ in self.zero_or_more():
                current += UnlexerRule(src=self.any_char())

        current += self.create_node(UnlexerRule(src='>'))
        return current
    DTD.min_depth = 0

    @depthcontrol
    def SCRIPTLET(self):
        current = self.create_node(UnlexerRule(name='SCRIPTLET'))
        choice = self.choice([0 if [0, 0][i] > self.unlexer.max_depth else w * self.unlexer.weights.get(('alt_16', i), 1) for i, w in enumerate([1, 1])])
        self.unlexer.weights[('alt_16', choice)] = self.unlexer.weights.get(('alt_16', choice), 1) * self.unlexer.cooldown
        if choice == 0:
            current += self.create_node(UnlexerRule(src='<?'))
            if self.unlexer.max_depth >= 0:
                for _ in self.zero_or_more():
                    current += UnlexerRule(src=self.any_char())

            current += self.create_node(UnlexerRule(src='?>'))
        elif choice == 1:
            current += self.create_node(UnlexerRule(src='<%'))
            if self.unlexer.max_depth >= 0:
                for _ in self.zero_or_more():
                    current += UnlexerRule(src=self.any_char())

            current += self.create_node(UnlexerRule(src='%>'))
        return current
    SCRIPTLET.min_depth = 0

    @depthcontrol
    def SEA_WS(self):
        current = self.create_node(UnlexerRule(name='SEA_WS'))
        if self.unlexer.max_depth >= 0:
            for _ in self.one_or_more():
                choice = self.choice([0 if [0, 0, 0][i] > self.unlexer.max_depth else w * self.unlexer.weights.get(('alt_25', i), 1) for i, w in enumerate([1, 1, 1])])
                self.unlexer.weights[('alt_25', choice)] = self.unlexer.weights.get(('alt_25', choice), 1) * self.unlexer.cooldown
                if choice == 0:
                    current += self.create_node(UnlexerRule(src=' '))
                elif choice == 1:
                    current += self.create_node(UnlexerRule(src='\t'))
                elif choice == 2:
                    if self.unlexer.max_depth >= 0:
                        for _ in self.zero_or_one():
                            current += self.create_node(UnlexerRule(src='\r'))

                    current += self.create_node(UnlexerRule(src='\n'))

        return current
    SEA_WS.min_depth = 0

    @depthcontrol
    def SCRIPT_OPEN(self):
        current = self.create_node(UnlexerRule(name='SCRIPT_OPEN'))
        current += self.create_node(UnlexerRule(src='<script'))
        if self.unlexer.max_depth >= 0:
            for _ in self.zero_or_more():
                current += UnlexerRule(src=self.any_char())

        current += self.create_node(UnlexerRule(src='>'))
        return current
    SCRIPT_OPEN.min_depth = 0

    @depthcontrol
    def STYLE_OPEN(self):
        current = self.create_node(UnlexerRule(name='STYLE_OPEN'))
        current += self.create_node(UnlexerRule(src='<style'))
        if self.unlexer.max_depth >= 0:
            for _ in self.zero_or_more():
                current += UnlexerRule(src=self.any_char())

        current += self.create_node(UnlexerRule(src='>'))
        return current
    STYLE_OPEN.min_depth = 0

    @depthcontrol
    def TAG_OPEN(self):
        current = self.create_node(UnlexerRule(name='TAG_OPEN'))
        current += self.create_node(UnlexerRule(src='<'))
        return current
    TAG_OPEN.min_depth = 0

    @depthcontrol
    def HTML_TEXT(self):
        current = self.create_node(UnlexerRule(name='HTML_TEXT'))
        if self.unlexer.max_depth >= 0:
            for _ in self.one_or_more():
                current += UnlexerRule(src=self.char_from_list(charset_0))

        return current
    HTML_TEXT.min_depth = 0

    @depthcontrol
    def TAG_CLOSE(self):
        current = self.create_node(UnlexerRule(name='TAG_CLOSE'))
        current += self.create_node(UnlexerRule(src='>'))
        return current
    TAG_CLOSE.min_depth = 0

    @depthcontrol
    def TAG_SLASH_CLOSE(self):
        current = self.create_node(UnlexerRule(name='TAG_SLASH_CLOSE'))
        current += self.create_node(UnlexerRule(src='/>'))
        return current
    TAG_SLASH_CLOSE.min_depth = 0

    @depthcontrol
    def TAG_SLASH(self):
        current = self.create_node(UnlexerRule(name='TAG_SLASH'))
        current += self.create_node(UnlexerRule(src='/'))
        return current
    TAG_SLASH.min_depth = 0

    @depthcontrol
    def TAG_EQUALS(self):
        current = self.create_node(UnlexerRule(name='TAG_EQUALS'))
        current += self.create_node(UnlexerRule(src='='))
        return current
    TAG_EQUALS.min_depth = 0

    @depthcontrol
    def TAG_NAME(self):
        current = self.create_node(UnlexerRule(name='TAG_NAME'))
        current += self.unlexer.TAG_NameStartChar()
        if self.unlexer.max_depth >= 1:
            for _ in self.zero_or_more():
                current += self.unlexer.TAG_NameChar()

        return current
    TAG_NAME.min_depth = 1

    @depthcontrol
    def TAG_WHITESPACE(self):
        current = self.create_node(UnlexerRule(name='TAG_WHITESPACE'))
        current += self.create_node(UnlexerRule(src=self.char_from_list(charset_1)))
        return current
    TAG_WHITESPACE.min_depth = 0

    @depthcontrol
    def HEXDIGIT(self):
        current = self.create_node(UnlexerRule(name='HEXDIGIT'))
        current += self.create_node(UnlexerRule(src=self.char_from_list(charset_2)))
        return current
    HEXDIGIT.min_depth = 0

    @depthcontrol
    def DIGIT(self):
        current = self.create_node(UnlexerRule(name='DIGIT'))
        current += self.create_node(UnlexerRule(src=self.char_from_list(charset_3)))
        return current
    DIGIT.min_depth = 0

    @depthcontrol
    def TAG_NameChar(self):
        current = self.create_node(UnlexerRule(name='TAG_NameChar'))
        choice = self.choice([0 if [1, 0, 0, 0, 1, 0, 0, 0][i] > self.unlexer.max_depth else w * self.unlexer.weights.get(('alt_46', i), 1) for i, w in enumerate([1, 1, 1, 1, 1, 1, 1, 1])])
        self.unlexer.weights[('alt_46', choice)] = self.unlexer.weights.get(('alt_46', choice), 1) * self.unlexer.cooldown
        if choice == 0:
            current += self.unlexer.TAG_NameStartChar()
        elif choice == 1:
            current += self.create_node(UnlexerRule(src='-'))
        elif choice == 2:
            current += self.create_node(UnlexerRule(src='_'))
        elif choice == 3:
            current += self.create_node(UnlexerRule(src='.'))
        elif choice == 4:
            current += self.unlexer.DIGIT()
        elif choice == 5:
            current += self.create_node(UnlexerRule(src='\u00B7'))
        elif choice == 6:
            current += self.create_node(UnlexerRule(src=self.char_from_list(range(768, 879))))
        elif choice == 7:
            current += self.create_node(UnlexerRule(src=self.char_from_list(range(8255, 8256))))
        return current
    TAG_NameChar.min_depth = 0

    @depthcontrol
    def TAG_NameStartChar(self):
        current = self.create_node(UnlexerRule(name='TAG_NameStartChar'))
        choice = self.choice([0 if [0, 0, 0, 0, 0, 0][i] > self.unlexer.max_depth else w * self.unlexer.weights.get(('alt_59', i), 1) for i, w in enumerate([1, 1, 1, 1, 1, 1])])
        self.unlexer.weights[('alt_59', choice)] = self.unlexer.weights.get(('alt_59', choice), 1) * self.unlexer.cooldown
        if choice == 0:
            current += self.create_node(UnlexerRule(src=self.char_from_list(charset_4)))
        elif choice == 1:
            current += self.create_node(UnlexerRule(src=self.char_from_list(range(8304, 8591))))
        elif choice == 2:
            current += self.create_node(UnlexerRule(src=self.char_from_list(range(11264, 12271))))
        elif choice == 3:
            current += self.create_node(UnlexerRule(src=self.char_from_list(range(12289, 55295))))
        elif choice == 4:
            current += self.create_node(UnlexerRule(src=self.char_from_list(range(63744, 64975))))
        elif choice == 5:
            current += self.create_node(UnlexerRule(src=self.char_from_list(range(65008, 65533))))
        return current
    TAG_NameStartChar.min_depth = 0

    @depthcontrol
    def SCRIPT_BODY(self):
        current = self.create_node(UnlexerRule(name='SCRIPT_BODY'))
        if self.unlexer.max_depth >= 0:
            for _ in self.zero_or_more():
                current += UnlexerRule(src=self.any_char())

        current += self.create_node(UnlexerRule(src='</script>'))
        return current
    SCRIPT_BODY.min_depth = 0

    @depthcontrol
    def SCRIPT_SHORT_BODY(self):
        current = self.create_node(UnlexerRule(name='SCRIPT_SHORT_BODY'))
        if self.unlexer.max_depth >= 0:
            for _ in self.zero_or_more():
                current += UnlexerRule(src=self.any_char())

        current += self.create_node(UnlexerRule(src='</>'))
        return current
    SCRIPT_SHORT_BODY.min_depth = 0

    @depthcontrol
    def STYLE_BODY(self):
        current = self.create_node(UnlexerRule(name='STYLE_BODY'))
        current += self.style_sheet()
        current += self.create_node(UnlexerRule(src='</style>'))
        return current
    STYLE_BODY.min_depth = 0

    @depthcontrol
    def STYLE_SHORT_BODY(self):
        current = self.create_node(UnlexerRule(name='STYLE_SHORT_BODY'))
        current += self.style_sheet()
        current += self.create_node(UnlexerRule(src='</>'))
        return current
    STYLE_SHORT_BODY.min_depth = 0

    @depthcontrol
    def ATTVALUE_VALUE(self):
        current = self.create_node(UnlexerRule(name='ATTVALUE_VALUE'))
        if self.unlexer.max_depth >= 0:
            for _ in self.zero_or_more():
                current += self.create_node(UnlexerRule(src=self.char_from_list(charset_5)))

        current += self.unlexer.ATTRIBUTE()
        return current
    ATTVALUE_VALUE.min_depth = 2

    @depthcontrol
    def ATTRIBUTE(self):
        current = self.create_node(UnlexerRule(name='ATTRIBUTE'))
        choice = self.choice([0 if [1, 1, 2, 1, 1][i] > self.unlexer.max_depth else w * self.unlexer.weights.get(('alt_75', i), 1) for i, w in enumerate([1, 1, 1, 1, 1])])
        self.unlexer.weights[('alt_75', choice)] = self.unlexer.weights.get(('alt_75', choice), 1) * self.unlexer.cooldown
        if choice == 0:
            current += self.unlexer.DOUBLE_QUOTE_STRING()
        elif choice == 1:
            current += self.unlexer.SINGLE_QUOTE_STRING()
        elif choice == 2:
            current += self.unlexer.ATTCHARS()
        elif choice == 3:
            current += self.unlexer.HEXCHARS()
        elif choice == 4:
            current += self.unlexer.DECCHARS()
        return current
    ATTRIBUTE.min_depth = 1

    @depthcontrol
    def ATTCHAR(self):
        current = self.create_node(UnlexerRule(name='ATTCHAR'))
        choice = self.choice([0 if [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0][i] > self.unlexer.max_depth else w * self.unlexer.weights.get(('alt_81', i), 1) for i, w in enumerate([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])])
        self.unlexer.weights[('alt_81', choice)] = self.unlexer.weights.get(('alt_81', choice), 1) * self.unlexer.cooldown
        if choice == 0:
            current += self.create_node(UnlexerRule(src='-'))
        elif choice == 1:
            current += self.create_node(UnlexerRule(src='_'))
        elif choice == 2:
            current += self.create_node(UnlexerRule(src='.'))
        elif choice == 3:
            current += self.create_node(UnlexerRule(src='/'))
        elif choice == 4:
            current += self.create_node(UnlexerRule(src='+'))
        elif choice == 5:
            current += self.create_node(UnlexerRule(src=','))
        elif choice == 6:
            current += self.create_node(UnlexerRule(src='?'))
        elif choice == 7:
            current += self.create_node(UnlexerRule(src='='))
        elif choice == 8:
            current += self.create_node(UnlexerRule(src=':'))
        elif choice == 9:
            current += self.create_node(UnlexerRule(src=';'))
        elif choice == 10:
            current += self.create_node(UnlexerRule(src='#'))
        elif choice == 11:
            current += self.create_node(UnlexerRule(src=self.char_from_list(charset_6)))
        return current
    ATTCHAR.min_depth = 0

    @depthcontrol
    def ATTCHARS(self):
        current = self.create_node(UnlexerRule(name='ATTCHARS'))
        if self.unlexer.max_depth >= 0:
            for _ in self.one_or_more():
                current += self.unlexer.ATTCHAR()

        if self.unlexer.max_depth >= 0:
            for _ in self.zero_or_one():
                current += self.create_node(UnlexerRule(src=' '))

        return current
    ATTCHARS.min_depth = 1

    @depthcontrol
    def HEXCHARS(self):
        current = self.create_node(UnlexerRule(name='HEXCHARS'))
        current += self.create_node(UnlexerRule(src='#'))
        if self.unlexer.max_depth >= 0:
            for _ in self.one_or_more():
                current += self.create_node(UnlexerRule(src=self.char_from_list(charset_7)))

        return current
    HEXCHARS.min_depth = 0

    @depthcontrol
    def DECCHARS(self):
        current = self.create_node(UnlexerRule(name='DECCHARS'))
        if self.unlexer.max_depth >= 0:
            for _ in self.one_or_more():
                current += self.create_node(UnlexerRule(src=self.char_from_list(charset_8)))

        if self.unlexer.max_depth >= 0:
            for _ in self.zero_or_one():
                current += self.create_node(UnlexerRule(src='%'))

        return current
    DECCHARS.min_depth = 0

    @depthcontrol
    def DOUBLE_QUOTE_STRING(self):
        current = self.create_node(UnlexerRule(name='DOUBLE_QUOTE_STRING'))
        current += self.create_node(UnlexerRule(src='"'))
        if self.unlexer.max_depth >= 0:
            for _ in self.zero_or_more():
                current += UnlexerRule(src=self.char_from_list(charset_9))

        current += self.create_node(UnlexerRule(src='"'))
        return current
    DOUBLE_QUOTE_STRING.min_depth = 0

    @depthcontrol
    def SINGLE_QUOTE_STRING(self):
        current = self.create_node(UnlexerRule(name='SINGLE_QUOTE_STRING'))
        current += self.create_node(UnlexerRule(src='\''))
        if self.unlexer.max_depth >= 0:
            for _ in self.zero_or_more():
                current += UnlexerRule(src=self.char_from_list(charset_10))

        current += self.create_node(UnlexerRule(src='\''))
        return current
    SINGLE_QUOTE_STRING.min_depth = 0

    def set_options(self):
        self.options = dict(tokenVocab="HTMLLexer", dot="any_unicode_char")

